services:
  rust_backend:
    container_name: rust_backend
    image: rust_backend-api
    build: ./rust_api
    env_file:
      - ./rust_api/src/.env
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: groot
      POSTGRES_DB: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5000:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: groot
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
    - 5001:80
    depends_on:
      - db
volumes:
  postgres_data:
  pgadmin_data:
